#!/usr/bin/env python
import os
import sys
from autoupdate import main as autoupdatemain


def main():
    if 2 > len(sys.argv):
        return False

    if "autoupdate" == sys.argv[1]:
        autoupdatemain()
    elif "hello" == sys.argv[1]:
        print("Why hello there! I'm inside python!")


if __name__ == '__main__':
    main()
