#!/usr/bin/env python
import os
import sys


def main():
    if 2 > len(sys.argv):
        return False
    if "autoupdate" == sys.argv[1]:
        from autoupdate import main as autoupdatemain
        autoupdatemain()
    elif "hello" == sys.argv[1]:
        print("Why hello there! I'm inside python!")
    elif "cron-sopupdate" == sys.argv[1]:
        from cron_trigger_autoupdate import trigger_autoupdate
        trigger_autoupdate()


if __name__ == '__main__':
    main()
