#!/usr/bin/env python
import os
import sys
from autoupdate import main as autoupdatemain
from cron_trigger_autoupdate import trigger_autoupdate


def main():
    if 2 > len(sys.argv):
        return False

    if "autoupdate" == sys.argv[1]:
        autoupdatemain()
    elif "hello" == sys.argv[1]:
        print("Why hello there! I'm inside python!")
    elif "cron-sopupdate" == sys.argv[1]:
        trigger_autoupdate()


if __name__ == '__main__':
    main()
